### ISSUE TITLE
Ruby 2.4+ breaks RestClient < 2.0.1

### ISSUE THREAD

**Issue by csfjeff** [PixarAnimationStudios/ruby-jss#24]
Not really a bug per se, more of a heads up that newer versions of Ruby break the version of RestClient that ruby-jss calls.  Running Ruby 2.4+ when I try to connect to the JSS I get the following error:

```
Traceback (most recent call last):
       10: from /usr/local/bin/irb:11:in `<main>'
        9: from (irb):2
        8: from /usr/local/bundle/gems/ruby-jss-0.12.0/lib/jss/api_connection.rb:446:in `connect'
        7: from /usr/local/bundle/gems/ruby-jss-0.12.0/lib/jss/api_connection.rb:1021:in `verify_server_version'
        6: from /usr/local/bundle/gems/ruby-jss-0.12.0/lib/jss/api_connection.rb:514:in `get_rsrc'
        5: from /usr/local/bundle/gems/rest-client-1.8.0/lib/restclient/resource.rb:51:in `get'
        4: from /usr/local/bundle/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
        3: from /usr/local/bundle/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `new'
        2: from /usr/local/bundle/gems/rest-client-1.8.0/lib/restclient/request.rb:163:in `initialize'
        1: from /usr/local/bundle/gems/rest-client-1.8.0/lib/restclient/request.rb:163:in `fetch'
KeyError (key not found: :ciphers)
```

Error re: RestClient discussed here:
https://github.com/rest-client/rest-client/issues/612

**Comment by HIMANSHU-ELIGIBLE** [comment]
https://github.com/PixarAnimationStudios/ruby-jss/pull/25

**Comment by glenfarclas17** [comment]
Fixed by HIMANSHU-ELIGIBLE - I'll get this released on rubygems.org in a day or two. Thanks everyone!
