### ISSUE TITLE
Strip command run on nil when setting description on new policy

### ISSUE THREAD

**Issue by cybertunnel** [PixarAnimationStudios/ruby-jss#31]
When creating a new policy and setting a description I get the following error:
**Command:** `new_policy.self_service_description = description`
**Version:** `ruby-jss (1.1.0b1)`

```Ruby
/Library/Ruby/Gems/2.3.0/gems/ruby-jss-1.1.0b1/lib/jss/api_object/self_servable.rb:350:in `self_service_description=': undefined method `strip!' for nil:NilClass (NoMethodError)
	from /Volumes/Untitled/JamfSync/server.rb:491:in `create_policy'
	from /Volumes/Untitled/JamfSync/sync_manager.rb:277:in `block (2 levels) in sync_policies_with'
	from /Volumes/Untitled/JamfSync/sync_manager.rb:272:in `each'
	from /Volumes/Untitled/JamfSync/sync_manager.rb:272:in `block in sync_policies_with'
	from /Volumes/Untitled/JamfSync/sync_manager.rb:269:in `each'
	from /Volumes/Untitled/JamfSync/sync_manager.rb:269:in `sync_policies_with'
	from ./sync.rb:59:in `block in <main>'
	from ./sync.rb:56:in `each'
	from ./sync.rb:56:in `<main>'```

**Comment by cybertunnel** [comment]
Might have been an error on my end. Going to do more testing and try to log the error if it occurs again.

**Comment by cybertunnel** [comment]
User error, was trying to play with a nil object.....
